name: fah-leveldb
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - nodejs
  - numpy
  - pandas
  - matplotlib
  - cython
  - pip
  - python=3.8.5
  - tqdm
  - pip:
    - nb_black
