name: fah-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - nodejs
  - numpy
  - pandas
  - matplotlib
  - cython
  - pip
  - requests
  - os
  - json
  - python=3.8.5
  - tqdm
  - pip:
    - nb_black
